channels:
     - conda-forge
dependencies:
     - dlib
     - numpy
     - scipy
     - opencv
     - face_recognition
     - streamlit
     - matplotlib
     - Pillow
     - tensorflow
     - keras
     - imageio
     - numpy==1.18.1
     - scikit-learn==0.22.2.post1
